#ifndef INPUT_H
#define INPUT_H
#include<stdint.h>
#include "queue.h"

#define INPUT_KEY_NONE 0
#define INPUT_KEY_UP 1
#define INPUT_KEY_DOWN 2
#define INPUT_KEY_UP_STRONG 3
#define INPUT_KEY_DOWN_STRONG 4
#define INPUT_KEY_START 5
#define INPUT_KEY_SELECT 6
#define INPUT_KEY_OK 7
#define INPUT_KEY_BACK 8
#define INPUT_KEY_SELECT_AND_START 9

#define INPUT_KEY_LONG_ADDITION 20
#define INPUT_KEY_UP_LONG INPUT_KEY_UP+INPUT_KEY_LONG_ADDITION
#define INPUT_KEY_DOWN_LONG INPUT_KEY_DOWN+INPUT_KEY_LONG_ADDITION
#define INPUT_KEY_UP_STRONG_LONG INPUT_KEY_UP_STRONG+INPUT_KEY_LONG_ADDITION
#define INPUT_KEY_DOWN_STRONG_LONG INPUT_KEY_DOWN_STRONG+INPUT_KEY_LONG_ADDITION
#define INPUT_KEY_START_LONG INPUT_KEY_START+INPUT_KEY_LONG_ADDITION
#define INPUT_KEY_SELECT_LONG INPUT_KEY_SELECT+INPUT_KEY_LONG_ADDITION
#define INPUT_KEY_OK_LONG INPUT_KEY_OK+INPUT_KEY_LONG_ADDITION
#define INPUT_KEY_BACK_LONG INPUT_KEY_BACK+INPUT_KEY_LONG_ADDITION

#define INPUT_KEY_OTHER 99

#define INPUT_WINDOW_RESIZE 100

void INPUT_init(Queue *outputQueue);
void INPUT_close();
void INPUT_switchAB(uint8_t abSwitch);

#endif
